### ISSUE TITLE
nave on vagrant seems to startup with a weird stylesheet

### ISSUE THREAD

**Issue by jaclu** [delving/nave#13]
On vagrant I get this layout:
![screenshot 2016-09-06 17 31 04](https://cloud.githubusercontent.com/assets/5046648/18279975/d6e5ba5c-7457-11e6-83b0-ededb149afc1.png)
On http://prod.brabantcloud.hubs.delving.org I get what seems to be the intended layout.

When I check in chrome dev tools, Network vagrant does not give any errors, so Im not sure what is at play here...

(you won't be able to test this until tomorrow when brabantcloud vagrant is committed, i write it now in order not to forget to report the issue)

**Comment by hanswesterbeek** [comment]
Assigning this back to you, @jaclu, until you can provide @kiivihal with a reproduction scenario.

**Comment by jaclu** [comment]
To reproduce:
Step 1 Deploy the brabantcloud vagrant 
Step 2 Go to the top url http://hub3-brab.localhost/

**Comment by hanswesterbeek** [comment]
Closing this as a known workaround exists and this will go away as of m 1.0.0
