### ISSUE TITLE
v1 API not consistently giving back full records (id query) - 500 error

### ISSUE THREAD

**Issue by zemyatin** [delving/nave#4]
v1 api requests to a full record with an id query give back a 500 error.

# **Het Scheepvaartmuseum**
## _Results query_
http://www.collectienederland.nl/api/search/v1/?query=*:*&hqf[]=delving_spec:hetscheepvaartmuseum&format=jsonp&facetBoolType=OR&lang=nl&rows=10&diw-version=1.1.0
### Url as sent from diw:
http://www.collectienederland.nl/api/search/v1/?id=dcn_hetscheepvaartmuseum_512824&format=jsonp&lang=nl&diw-version=1.1.0&mlt.filterkey=delving_spec:hetscheepvaartmuseum
### Url rewritten by nave
http://www.collectienederland.nl/api/search/v1/dcn_hetscheepvaartmuseum_512824/?format=jsonp&lang=nl&diw-version=1.1.0&mlt.filterkey=delving_spec%3Ahetscheepvaartmuseum

# **Dordrecht Bouwhistorie**
## _Results query:_
http://www.collectienederland.nl/api/search/v1/?query=*:*&hqf[]=delving_spec:dordrecht-bouwhistorie&format=jsonp&facetBoolType=OR&lang=nl&rows=10&diw-version=1.1.0
### Url as sent from diw:
http://www.collectienederland.nl/api/search/v1/?id=dcn_dordrecht-bouwhistorie_H102-001&format=jsonp&lang=nl&diw-version=1.1.0&mlt.filterkey=delving_spec:dordrecht-bouwhistorie
### Url rewritten by nave
http://www.collectienederland.nl/api/search/v1/dcn_dordrecht-bouwhistorie_H102-001/?format=jsonp&callback=jQuery112401571636615158991_1471947640969&_=1471947640970&mlt.filterkey=delving_spec%3Adordrecht-bouwhistorie&diw-version=1.1.0&lang=nl

**Comment by kiivihal** [comment]
This issue has been fixed in version 0.9.2
