### ISSUE TITLE
Nave bulk API throws exception when saving

### ISSUE THREAD

**Issue by hanswesterbeek** [delving/nave#50]
![image001](https://cloud.githubusercontent.com/assets/233545/21183005/38596724-c206-11e6-8ccd-f6063716c3f3.png)

**Comment by eddiesmit** [comment]
[Narthex-save-error.pdf](https://github.com/delving/nave/files/651883/Narthex-save-error.pdf)
complete logfile toegevoegd

**Comment by kiivihal** [comment]
This issue is related to an deployment issue and proper initialisation of the Postgresql database. This issue is not caused by the API, therefor ethis issue will be closed.
